Feature/93 ingress service
perber/kdd pull request #101
Opened 2023-02-22 21:51 UTC by rati3l

Frontend for list view of services, config maps, secrets and ingresses

2023-02-27 09:28 UTC, perber requested changes

2023-02-27 09:28 UTC, perber commented on _ui/src/clients/response_types/autogen.tsx
> +export type ByConfigMapName = ConfigMap[]
please exclude this things in the script. 
It is not necessary.

2023-02-27 09:28 UTC, perber commented on _ui/src/components/commons/PageContainer.tsx
> +import { getClusterNavigation, getRefreshIntervals, getWorkloadNavigation, getMiscNavigation, NavItemConfig, RefreshIntervalConfig } from '../../navigation';
I wouldn`t call it misc. 
service discovery or any other suggestions?

2023-02-27 09:28 UTC, perber commented on _ui/src/components/commons/PageContainer.tsx
> +                    {getMiscNavigation().map((item: NavItemConfig, index: number) => {
I wouldn`t call it misc.
service discovery or any other suggestions?

2023-02-27 09:28 UTC, perber commented on _ui/src/navigation/index.tsx
> +export const getMiscNavigation = (): Array<NavItemConfig> => {
I wouldn`t call it misc.
service discovery or any other suggestions?
for configmaps & secrets - configuration?

2023-02-27 09:28 UTC, perber commented on _ui/src/components/datagrids/transformers/index.tsx
> +    const transformDataForIngressDataGrid = (nodes: Array<Ingress>): Array<IngressDataGrid> => {
To retrieve the data as is. 
We could implement a standard transformer function. 
The standard transformer function could be added instead of the return value.

Then we should do something like this Array<ServiceDataGrid|SecretDataGrid> to allow multiple types to return.

2023-02-27 09:28 UTC, perber commented on _ui/src/components/datagrids/transformers/index.tsx
> +        transformDataForIngressDataGrid,
If you would like to use a "Standard Transformer you can write this":
transformDataForIngressDataGrid: "StandardTransformer"

2023-02-27 09:29 UTC, perber requested changes

2023-02-27 09:29 UTC, perber commented on _ui/src/components/datagrids/transformers/index.tsx
> +        return nodes
if you keep that functions, please rename nodes

2023-03-06 17:34 UTC, rati3l commented on _ui/src/clients/response_types/autogen.tsx
> +export type ByConfigMapName = ConfigMap[]
script is now patched to remove this types

2023-03-06 17:48 UTC, rati3l commented on _ui/src/components/commons/PageContainer.tsx
> +import { getClusterNavigation, getRefreshIntervals, getWorkloadNavigation, getMiscNavigation, NavItemConfig, RefreshIntervalConfig } from '../../navigation';
hm, i wanted to do like a collective term for all of the little resources that don't need separate grouping. 
I've moved those to "Network" and "Configuration"

2023-03-06 18:53 UTC, rati3l commented on _ui/src/components/datagrids/transformers/index.tsx
> +    const transformDataForIngressDataGrid = (nodes: Array<Ingress>): Array<IngressDataGrid> => {
i've implemented standard transformer

2023-03-06 20:08 UTC, perber requested changes

2023-03-06 20:08 UTC, perber commented on _ui/src/components/datagrids/transformers/index.tsx
> +                                }
It seems to be the formatting is broken.
Maybe we should start to use linting in the pipeline.

2023-03-06 20:08 UTC, perber commented on _ui/src/components/tables/PodInfoRow.tsx
> +                <TableCell><Link href={buildLink(WORKLOAD_TYPE_PODS, pod.workload_info.namespace, pod.workload_info.workload_name)}>{pod.workload_info.workload_name}</Link></TableCell>
What you wanted to do here, there is still Workload in the url.

2023-03-06 20:08 UTC, perber commented on _ui/src/clients/kdd.ts
> +        return data.data
secrets is not correct there should be secret.

2023-03-06 20:08 UTC, perber commented on _ui/src/clients/kdd.ts
> +        const { data } = await axios.get(`/api/v1/namespaced/configmaps/${namespace}/${name}`, { headers })
there it should be configmap

2023-03-06 21:48 UTC, rati3l commented on _ui/src/components/tables/PodInfoRow.tsx
> +                <TableCell><Link href={buildLink(WORKLOAD_TYPE_PODS, pod.workload_info.namespace, pod.workload_info.workload_name)}>{pod.workload_info.workload_name}</Link></TableCell>
I thought we don't need separate functions to build links for workloads and the rest of the namespace resources - buildLink uses isWorkloadType function and builds the URL accordingly.

2023-03-06 21:49 UTC, rati3l commented on _ui/src/clients/kdd.ts
> +        return data.data
yup, fixed

2023-03-06 21:54 UTC, rati3l commented on _ui/src/components/datagrids/transformers/index.tsx
> +                                }
no idea how that happened... 
for sure I should use linter on my end :)

2023-03-06 23:42 UTC, perber commented on _ui/src/components/tables/PodInfoRow.tsx
> +                <TableCell><Link href={buildLink(WORKLOAD_TYPE_PODS, pod.workload_info.namespace, pod.workload_info.workload_name)}>{pod.workload_info.workload_name}</Link></TableCell>
Yeah we could do it this way. Ah sorry. I haven`t check that this is in the PodInfoRow it was my fault.

2023-03-06 23:45 UTC, perber approved these changes
lgtm ... whoop, lets merge it ;)

2023-03-07 06:16 UTC, merged