Feature/33 config module
perber/kdd pull request #57
Opened 2023-02-08 22:55 UTC by rati3l

Config module, k8s deployment, and Dockerfile for the app.
Docker image is stored on mu dockerhub for now (ratiel/kdd). To test the k8s deployments it should be enough to run kubectl apply on the manifest file.

I've wrote a short doc in the readme about the variables available.

2023-02-09 00:09 UTC, perber reviewed
Nodeport ist good for the beginning. We should also add later an Ingress configuration. 

We just need to create a ticket for Ingress and Helm.

2023-02-13 08:30 UTC, rati3l commented
@perber this is ready for merge

2023-02-13 12:51 UTC, perber requested changes

2023-02-13 12:54 UTC, rati3l commented on internal/config/app_config.go
> +	return
I wanted to print config struct, and you need to use sugar for that - data for the regular option needs to be structured.

2023-02-13 12:56 UTC, rati3l commented on internal/config/app_config.go
> +	env_prefix := "KDD_"
habits :D i've fixed that

2023-02-13 14:04 UTC, perber approved these changes
lgtm

2023-02-13 14:47 UTC, merged